#ifndef __OPERATOR_TOOLS__
#define __OPERATOR_TOOLS__


enum COMPARISON_OPERATOR {
  TO_EQUAL,
  TO_NOT_EQUAL,
  TO_BE_GREATER_THAN,
  TO_BE_LESS_THAN,
  TO_BE_GREATER_THAN_OR_EQUAL_TO,
  TO_BE_LESS_THAN_OR_EQUAL_TO
};


#endif // __OPERATOR_TOOLS__
